---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: airflow-admin-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: airflow-admin
  apiGroup: rbac.authorization.k8s.io
