---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: airflow-secrets
data:
{{ (.Files.Glob "files/secrets/airflow/*").AsSecrets | indent 2}}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ingress-auth
data:
{{ (.Files.Glob "files/secrets/ingress/*").AsSecrets | indent 2 }}
