ingress:
  host: <your host here>

image:
  repository: xxxxxxxx.dkr.ecr.< region >.amazonaws.com/airflow
  tag: latest
  autoTag: false

dags_image:
  repository: xxxxxxx.dkr.ecr.< region >.amazonaws.com/airflow-dags
  tag: <build number>